language: rust
rust:
  - nightly

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: windows
    - os: osx

script:
  - cargo build --release --features=opencl,simd
