language: rust
rust:
  - nightly
  
os:
  - windows
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

script:
  - cargo build --release --features=opencl,simd
