language: rust
rust:
  - nightly

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
      script: cargo build --release --features=simd
    - os: windows
      script: cargo build --release --features=simd
    - os: osx
      script:
        - cargo build --release --features=simd
        - cargo build --release --features=opencl,simd # gpu build requires OpenCL, only osx has it
