language: rust
rust:
  - nightly
cache: cargo

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
            - g++-7
            - ocl-icd-opencl-dev
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: windows
      install: choco install -y opencl-intel-cpu-runtime 
    - os: osx
      
script:
  - cargo build --release --features=simd
  - cargo build --release --features=opencl,simd
